default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: rails
  password: root
  host: localhost


development:
  <<: *default
  database: hello_rails_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: hello_rails_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: sample_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
